### ISSUE TITLE
Unable to run errand "upload-kibana-objects" - Error filling in template 'run' (line 113: Can't find property '["elasticsearch.host"]')

### ISSUE THREAD

**Issue by jstaley** [cloudfoundry-community/logsearch-for-cloudfoundry#257]
When running the upload-kibana-objects errand using version 205.0.0 I receive the error: - Error filling in template 'run' (line 113: Can't find property '["elasticsearch.host"]')

```
- name: upload-kibana-objects
  azs: [ az1, az2, az3 ]
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  jobs:
  - { name: upload-kibana-objects, release: logsearch-for-cloudfoundry }
  networks:
  - name: dynamic
  stemcell: trusty
  vm_type: 1cpu_2gbram_4gbdisk
  properties:
    elasticsearch:
      host: <HOST_IP>
      port: 9200
    cloudfoundry:
      firehose_events: LogMessage,Error
    kibana_objects:
      upload_predefined_kibana_objects: true # Default value. Whether to upload Kibana objects (defaults predefined in this job) or not.
      upload_data_files: []  # List of text files to put in API endpoint /_bulk
```

For reference sake, the release was upgraded from 202.0 and I am using logsearch version 207.0. The deployment went alright and I everything appears to be working with the exception of being able to upload the new objects.

Any help is appreciated.
Kind Regards,
Josh
